### PR TITLE
Release `v1.2.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v1.2.0` release.
Here you can find all related translations changes: [v1.1.1.1220...master](https://github.com/flarum-lang/chinese-simplified/compare/v1.1.1.1220...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## v1.2.0

**例行更新**:

* 更新 Flarum 核心翻译.

**新增扩展程序翻译**:

* [`akr/chevereto`](https://github.com/AKR-Developers/flarum-chevereto)
* [`annonny/flarum-dice`](https://github.com/mizhiyugan529/flarum-dice)
* [`archlinux-de/flarum-click-image`](https://github.com/archlinux-de/flarum-click-image)
* [`blessing/flarum-oauth-client`](https://github.com/bs-community/flarum-oauth-client)
* [`blomstra/flag-duplicates`](https://github.com/blomstra/flarum-ext-flag-duplicate)
* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`blomstra/notification-deleter`](https://github.com/blomstra/flarum-ext-notification-deleter)
* [`blomstra/oauth-slack`](https://github.com/blomstra/flarum-ext-oauth-slack)
* [`blomstra/s3-assets`](https://extiverse.com/extension/blomstra/s3-assets)
* [`blomstra/secondary-tags-toggler`](https://github.com/blomstra/flarum-ext-secondary-tags-toggler)
* [`blomstra/sort-order-toggle`](https://github.com/blomstra/flarum-ext-sort-order-toggle)
* [`blomstra/trello`](https://github.com/blomstra/flarum-ext-trello)
* [`blomstra/user-filter`](https://github.com/blomstra/flarum-ext-user-filter)
* [`blomstra/usercard-stats`](https://github.com/blomstra/flarum-ext-usercard-stats)
* [`blomstra/welcome-login`](https://github.com/blomstra/flarum-ext-welcome-login)
* [`clarkwinkelmann/flarum-ext-anonymous-posting`](https://github.com/clarkwinkelmann/flarum-ext-anonymous-posting)
* [`clarkwinkelmann/flarum-ext-composer-page`](https://github.com/clarkwinkelmann/flarum-ext-composer-page)
* [`clarkwinkelmann/flarum-ext-default-image-alt`](https://github.com/clarkwinkelmann/flarum-ext-default-image-alt)
* [`clarkwinkelmann/flarum-ext-discussion-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-discussion-bookmarks)
* [`clarkwinkelmann/flarum-ext-discussion-open-position`](https://github.com/clarkwinkelmann/flarum-ext-discussion-open-position)
* [`clarkwinkelmann/flarum-ext-jwt-cookie-login`](https://github.com/clarkwinkelmann/flarum-ext-jwt-cookie-login)
* [`clarkwinkelmann/flarum-ext-mass-actions`](https://github.com/clarkwinkelmann/flarum-ext-mass-actions)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`datlechin/flarum-copy-links`](https://github.com/datlechin/flarum-copy-links)
* [`datlechin/flarum-link-preview`](https://github.com/datlechin/flarum-link-preview)
* [`datlechin/flarum-posted-on`](https://github.com/datlechin/flarum-posted-on)
* [`datlechin/flarum-silent-edit`](https://github.com/datlechin/flarum-silent-edit)
* [`datlechin/flarum-tag-passwords`](https://github.com/datlechin/flarum-tag-passwords)
* [`flamarkt/taxonomies`](https://github.com/flamarkt/taxonomies)
* [`fof/default-user-preferences`](https://github.com/FriendsOfFlarum/default-user-preferences)
* [`kilowhat/flarum-ext-rich-embeds`](https://extiverse.com/extension/kilowhat/flarum-ext-rich-embeds)
* [`littlecxm/flarum-reply-to-see`](https://github.com/littlecxm/flarum-reply-to-see)
* [`swaggymacro/only-starter`](https://github.com/SwaggyMacro/OnlyStarter)
* [`sycho/flarum-private-facade`](https://extiverse.com/extension/sycho/flarum-private-facade)
* [`webbinaro/flarum-affiliator`](https://github.com/eddiewebb/flarum-affiliator)

**更新扩展程序翻译**:

* [`afrux/forum-widgets-core`](https://github.com/afrux/forum-widgets-core)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`askvortsov/flarum-auto-moderator`](https://github.com/askvortsov1/flarum-auto-moderator)
* [`blomstra/realtime`](https://extiverse.com/extension/blomstra/realtime)
* [`clarkwinkelmann/flarum-ext-carving-contest`](https://github.com/clarkwinkelmann/flarum-ext-carving-contest)
* [`clarkwinkelmann/flarum-ext-colorful-borders`](https://github.com/clarkwinkelmann/flarum-ext-colorful-borders)
* [`davwheat/flarum-ext-ads`](https://github.com/davwheat/flarum-ext-ads)
* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`fof/analytics`](https://github.com/FriendsOfFlarum/analytics)
* [`fof/ban-ips`](https://github.com/FriendsOfFlarum/ban-ips)
* [`fof/best-answer`](https://github.com/FriendsOfFlarum/best-answer)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/discussion-language`](https://github.com/FriendsOfFlarum/discussion-language)
* [`fof/gamification`](https://github.com/FriendsOfFlarum/gamification)
* [`fof/merge-discussions`](https://github.com/FriendsOfFlarum/merge-discussions)
* [`fof/nightmode`](https://github.com/FriendsOfFlarum/nightmode)
* [`fof/oauth`](https://github.com/FriendsOfFlarum/oauth)
* [`fof/pretty-mail`](https://github.com/FriendsOfFlarum/pretty-mail)
* [`fof/reactions`](https://github.com/FriendsOfFlarum/reactions)
* [`fof/sentry`](https://github.com/FriendsOfFlarum/sentry)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/sitemap`](https://github.com/FriendsOfFlarum/sitemap)
* [`fof/socialprofile`](https://github.com/FriendsOfFlarum/socialprofile)
* [`fof/subscribed`](https://github.com/FriendsOfFlarum/subscribed)
* [`fof/upload`](https://github.com/FriendsOfFlarum/upload)
* [`fof/user-directory`](https://github.com/FriendsOfFlarum/user-directory)
* [`glowingblue/redis-setup`](https://github.com/glowingblue/flarum-ext-redis-setup)
* [`ianm/follow-users`](https://github.com/imorland/follow-users)
* [`ianm/syndication`](https://github.com/imorland/syndication)
* [`justoverclock/custom-header`](https://github.com/justoverclockl/custom-header)
* [`justoverclock/flarum-ext-hashtag`](https://github.com/justoverclockl/flarum-ext-hashtag)
* [`justoverclock/related-discussions`](https://extiverse.com/extension/justoverclock/related-discussions)
* [`kilowhat/flarum-ext-audit-pro`](https://extiverse.com/extension/kilowhat/flarum-ext-audit-pro)
* [`malago/flarum-achievements`](https://github.com/malago86/flarum-achievements)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`nearata/flarum-ext-embed-video`](https://github.com/Nearata/flarum-ext-embed-video)
* [`nearata/flarum-ext-twofactor`](https://github.com/Nearata/flarum-ext-twofactor)
* [`spookygames/flarum-ext-auth-keycloak`](https://github.com/spookygames/flarum-ext-auth-keycloak)
* [`the-turk/flarum-nodp`](https://github.com/the-turk/flarum-nodp)
* [`the-turk/flarum-stickiest`](https://github.com/the-turk/flarum-stickiest)
* [`v17development/flarum-blog`](https://github.com/v17development/flarum-blog)
* [`v17development/flarum-support`](https://extiverse.com/extension/v17development/flarum-support)
* [`v17development/flarum-user-badges`](https://github.com/v17development/flarum-user-badges)
* [`xelson/flarum-ext-chat`](https://github.com/Xelson/flarum-ext-chat)
* [`zerosonesfun/flarum-bbcode-button`](https://github.com/zerosonesfun/flarum-bbcode-button)
* [`zerosonesfun/expired-posts`](https://github.com/zerosonesfun/expired-posts)

全部变化：[v1.1.1.1220...v1.2.0](https://github.com/flarum-lang/chinese-simplified/compare/v1.1.1.1220...v1.2.0)

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@littlegolden Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by littlegolden** [comment]
good job bro, this is so cool

**Comment by rob006** [comment]
@littlegolden is there anything blocking this release? Right now most of users of this language pack is using last stable release, which is from December 2021.

**Comment by littlegolden** [comment]
> @littlegolden is there anything blocking this release? Right now most of users of this language pack is using last stable release, which is from December 2021.

it's been busy days, and there are still some translations need to be reviewed. It is expected to be released before October 8th.

**Comment by rob006** [comment]
@littlegolden You should not merge this PR manually, just approve it and bot will handle the rest. For this release I tagged it manually, but in the future please follow instructions in the first comment.

**Pull request merged**
